### ISSUE TITLE
Bug: Unintended slanted typeface w\ solution suggestion given

### ISSUE THREAD

**Issue by Riseley** [saadq/resumake#46]
Under the Projects header with, the code automatically generated \sl outside the intended slanted "Tools Used"

Example generated by resumake:
```
\header{Projects}
{\textbf{My Awesome Python Project}} \sl {Python, C++} \\
This project helped 10k+ volunteers blah blah blah. \\
\vspace*{2mm}
```

The code above is not desirable because starting from the second project, everything below will be in slanted typeface mode. (Until the next header comes in)

Suggested solution:
```
... {\sl <First Tool Used>, <Second Tool Used>}
```

Thank you for this awesome project. I would have requested a pull request but my web development skills aren't good enough.

**Comment by saadq** [comment]
Hey @Riseley, thanks for reporting this! Do you know which template you were using when you faced this issue?

**Comment by Riseley** [comment]
Oh it was Template 1. I did not try this on other templates.

**Comment by saadq** [comment]
Hmm, I can't seem to replicate this issue with template 1... would you be able to download the JSON for the resume and attach it here so I can try it out as well?

**Comment by saadq** [comment]
Ahh, actually I was able to replicate it when I removed some of my other sections... that's weird. Will look into it!

**Comment by saadq** [comment]
@Riseley so I think what was happening was that somewhere in my additional sections the formatting was getting fixed. Obviously that's not something that should be relied on, so the fix would be to do as you mentioned.

The line of code that would need to be fixed is here:

https://github.com/saadq/resumake/blob/2c83bb366822a85c340ccfe4a92be47031c4a3b8/app/server/src/generator/templates/template1/index.js#L210

The `\\sl` would need to be moved as you suggested into the curly bracket. Would you like to make the PR to fix this?

**Comment by Riseley** [comment]
Oh really? Thanks! Let me do a PR now.
